// nuxt-example/components/forecast-table.vue
<template>
  <div class="max-w-screen-sm mx-auto">
    <transition name="fade" appear mode="out-in">
      <div v-if="forecast" :key="forecast.placeName">
        <p class="text-2xl font-semibold py-6 text-center">
          Forecast between {{ providedDates }}
          at
          {{ forecast.placeName }}.
        </p>
        <v-expansion-panels>
          <v-expansion-panel v-for="(item, i) in forecast.daily" :key="i">
            <v-expansion-panel-header
              ><div class="grid grid-cols-4">
                <div>
                  <p class="text-xl font-semibold">
                    {{ moment.unix(item.dt).format('ddd') }}
                  </p>
                  <p class="text-gray-500">
                    {{ moment.unix(item.dt).format('MMM') }}
                    {{ moment.unix(item.dt).format('Do') }}
                  </p>
                </div>

                <div>
                  <i class="wi text-4xl" :class="item.weather[0].main"></i>
                </div>
                <div class="">
                  {{ firstLetterUppercase(item.weather[0].description) }}
                </div>
                <div>
                  <span class="text-4xl font-bold"
                    >{{ Math.trunc(item.temp.max) }}°</span
                  >
                  <span class="text-gray-500"
                    >/{{ Math.trunc(item.temp.min) }}°</span
                  >
                </div>
              </div>
            </v-expansion-panel-header>
            <v-expansion-panel-content>
              {{ summary(item) }}
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-expansion-panels>
      </div>
      <div v-else key="didyou" class="mt-8">
        <p class="font-thin mb-4">Before you fetch, did you know:</p>
        <div class="ml-2 space-y-4">
          <p>- Average global temperature is up 0.94°C (1.7°F) since 1880?</p>
          <p>
            - The wind doesn’t make a sound until it blows against an object?
          </p>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
import moment from 'moment'
export default {
  data() {
    return {
      moment,
    }
  },
  computed: {
    providedDates() {
      return `${moment.unix(this.forecast.daily[0].dt).format('MMM')} ${moment
        .unix(this.forecast.daily[0].dt)
        .format('Do')} - ${moment
        .unix(this.forecast.daily[this.forecast.daily.length - 1].dt)
        .format('MMM')} ${moment
        .unix(this.forecast.daily[this.forecast.daily.length - 1].dt)
        .format('Do')}
      `
    },
    forecast() {
      return this.$store.state.forecast
    },
  },

  methods: {
    summary(item) {
      return `${this.firstLetterUppercase(
        item.weather[0].description
      )} throughout day. Feeling temperature is ${Math.trunc(
        item.feels_like.day
      )}° at ${this.forecast.placeName}.`
    },
    firstLetterUppercase(str) {
      return str.charAt(0).toUpperCase() + str.slice(1)
    },
  },
}
</script>

<style lang="scss" scoped></style>

// react-example/src/components/ForecastTable.js
import React, { useState } from 'react';
import moment from 'moment';

import {
	Accordion,
	AccordionSummary,
	AccordionDetails,
	Grid,
	Box,
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import { grey } from '@mui/material/colors';

export default function ForecastTable({ data }) {
	const [expanded, setExpanded] = useState(false);

	const handleChange = (panel) => (event, isExpanded) => {
		setExpanded(isExpanded ? panel : false);
	};

	const { daily: dailyArr, placeName } = data;

	const firstLetterUppercase = (str) => {
		return str.charAt(0).toUpperCase() + str.slice(1);
	};

	const summary = (item) => {
		return `${firstLetterUppercase(
			item.weather[0].description
		)} throughout day. Feeling temperature is ${Math.trunc(
			item.feels_like.day
		)}° at ${placeName}.`;
	};

	const providedDates = () => {
		return `${moment.unix(dailyArr[0].dt).format('MMM')} ${moment
			.unix(dailyArr[0].dt)
			.format('Do')} - ${moment
			.unix(dailyArr[dailyArr.length - 1].dt)
			.format('MMM')} ${moment
			.unix(dailyArr[dailyArr.length - 1].dt)
			.format('Do')}
    `;
	};
	return (
		<>
			<Box
				component="p"
				sx={{
					fontSize: '24px',
					fontWeight: 'bold',
					textAlign: 'center',
				}}
			>
				Forecast between {providedDates()} at {placeName}.
			</Box>

			{dailyArr.map((day, i) => {
				return (
					<Accordion
						key={i}
						expanded={expanded === i}
						onChange={handleChange(i)}
					>
						<AccordionSummary
							expandIcon={<ExpandMoreIcon />}
							aria-controls="panel1a-content"
							id="panel1a-header"
						>
							<Grid
								container
								sx={{
									textAlign: 'center',
								}}
							>
								<Grid item xs={3}>
									<Box
										component="p"
										sx={{
											fontSize: '20px',
											fontWeight: 'bold',
											margin: ' 0 0 4px 0',
										}}
									>
										{moment.unix(day.dt).format('ddd')}
									</Box>
									<Box
										sx={{
											color: grey[500],
											fontSize: '15px',
										}}
									>
										{moment.unix(day.dt).format('MMM')} <span> </span>
										{moment.unix(day.dt).format('Do')}
									</Box>
								</Grid>
								<Grid item xs={3}>
									<i
										className={`wi ${day.weather[0].main}`}
										style={{ fontSize: '40px' }}
									></i>
								</Grid>
								<Grid
									item
									xs={3}
									sx={{
										fontSize: '20px',
									}}
								>
									{firstLetterUppercase(day.weather[0].description)}
								</Grid>
								<Grid item xs={3}>
									<Box
										component="span"
										sx={{
											fontSize: '30px',
											fontWeight: 'bold',
										}}
									>
										{Math.trunc(day.temp.max)}°
									</Box>
									<Box
										component="span"
										sx={{
											fontSize: '20px',
											color: grey[500],
										}}
									>
										/{Math.trunc(day.temp.min)}°
									</Box>
								</Grid>
							</Grid>
						</AccordionSummary>
						<AccordionDetails sx={{ textAlign: 'center' }}>
							{summary(day)}
						</AccordionDetails>
					</Accordion>
				);
			})}
		</>
	);
}
